과제 : 
https://sg.sbiz.or.kr/godo/stat/upso.sg 사이트에서 담당 지역 상권 정보 크롤링하기

## 기본 환경설정

In [ ]:
#구글 드라이브 접속 권한 획득
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
#ubuntu 업데이트
!apt-get update

In [ ]:
#셀레늄 패키지 다운
!pip install selenium

In [ ]:
#크롬드라이버 다운
!apt install chromium-chromedriver
!cp /usr/lib/chromium-browser/chromedriver /usr/bin

In [ ]:
#크롬드라이버 경로 설정
import sys
sys.path.insert(0, '/usr/lib/chromium-browser/chromedriver')

In [ ]:
#코랩에서 작동하도록 옵션 설정
from selenium import webdriver
options = webdriver.ChromeOptions()
options.add_argument('-headless')
options.add_argument('-no-sandbox')
options.add_argument('-disable-dev-shm-usage')

In [ ]:
#정보 요청 라이브러리
!pip install requests

In [ ]:
#구문 분석 라이브러리
!pip install lxml

In [ ]:
#셀레늄 라이브러리
!pip install webdriver_manager

In [ ]:
#셀레늄 라이브러리 불러오기
from selenium import webdriver

from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager

#셀레늄에서 html문서가 생성될 때까지 대기하는 함수 불러오기
from selenium.webdriver.support.ui import WebDriverWait

#셀레늄에서 조건을 걸어줄 수 있는 함수 불러오기
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By

In [ ]:
import time

In [ ]:
import pandas as pd

In [ ]:
#긁어오기 시작
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys

## 스크래핑

### 지역현황

#### 광주

In [ ]:
# 웹 드라이버 객체 생성
browser = webdriver.Chrome('chromedriver', options = options)

In [ ]:
browser.get('https://sg.sbiz.or.kr/godo/stat/area.sg')

In [ ]:
#시군구 선택 
browser.find_element("xpath","/html/body/div[1]/div[2]/div[1]/div[2]/div/div/div[1]/div/div[1]/ul/li[1]/div/div[2]/a").click()

In [ ]:
#광주 선택
browser.find_element("xpath", "/html/body/div[2]/div/div[2]/div/div[1]/div/ul/li[1]/div/ul/li[6]/label").click()

In [ ]:
#확인 선택
browser.find_element("xpath","/html/body/div[2]/div/div[2]/div/div[2]/a[2]/span").click()

In [ ]:
#현황보기 선택 
browser.find_element("xpath","/html/body/div[1]/div[2]/div[1]/div[2]/div/div/div[1]/div/div[2]/a").click()

In [ ]:
kj_table = browser.find_elements(By.CSS_SELECTOR,'#tableBody > tr > td')
kj_result = []
for a in kj_table:
  kj_result.append(a.text)

In [ ]:
#리스트 분할 함수
def list_chunk(lst, n):
  return [lst[i:i+n] for i in range(0, len(lst), n)]

In [ ]:
kj_result = list_chunk(kj_result, 9) # 한번만 실행할 것!
kj_result

In [ ]:
mycolumns = ["행정구역", "총가구수", "총인구수", "주요시설수", "집객시설수", "아파트 면적(1m²)당 기준시가(원)", "업소수", "업소당 가구수", "업소당 시설물수 "]

In [ ]:
kj_df = pd.DataFrame(kj_result, columns = mycolumns)

In [ ]:
kj_df #완료

,행정구역,총가구수,총인구수,주요시설수,집객시설수,아파트 면적(1m²)당 기준시가(원),업소수,업소당 가구수,업소당 시설물수
0,광주광역시,"585,113","1,476,513","6,464","7,782","4,909,203","82,825",7,0.17
1,┗ 동구,"42,900","91,393",722,"1,099","3,663,949","10,468",4,0.17
2,┗ 서구,"122,089","308,479","1,472","1,910","5,206,981","20,172",6,0.17
3,┗ 남구,"88,114","222,181",952,800,"4,941,637","9,057",10,0.19
4,┗ 북구,"181,737","450,822","1,853","2,257","4,598,536","23,337",8,0.18
5,┗ 광산구,"150,274","403,638","1,465","1,716","5,365,703","19,791",8,0.16

In [280]:
kj_df.to_csv("광주_지역현황.csv", index = None) #csv 파일로 내보내기

#### 대구

In [ ]:
#시군구 선택 
browser.find_element("xpath","/html/body/div[1]/div[2]/div[1]/div[2]/div/div/div[1]/div/div[1]/ul/li[1]/div/div[2]/a").click()

In [ ]:
#대구 선택
browser.find_element("xpath", "/html/body/div[2]/div/div[2]/div/div[1]/div/ul/li[1]/div/ul/li[4]/label").click()

In [ ]:
#확인 선택
browser.find_element("xpath","/html/body/div[2]/div/div[2]/div/div[2]/a[2]/span").click()

In [ ]:
#현황보기 선택 
browser.find_element("xpath","/html/body/div[1]/div[2]/div[1]/div[2]/div/div/div[1]/div/div[2]/a").click()

In [ ]:
tk_table = browser.find_elements(By.CSS_SELECTOR,'#tableBody > tr > td')
tk_result = []
for a in tk_table:
  tk_result.append(a.text)

In [ ]:
tk_result = list_chunk(tk_result, 9) # 한번만 실행할 것!
tk_result

In [ ]:
tk_df = pd.DataFrame(tk_result, columns = mycolumns)
tk_df

In [281]:
tk_df.to_csv("대구_지역현황.csv", index = None)

#### 전북

팝업창 스크롤을 내리는 추가적인 작업 필요

In [ ]:
#셀레늄 라이브러리 불러오기
from selenium import webdriver

from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager

#키보드 자판을 입력할 수 있는 셀레늄 함수 불러오기
from selenium.webdriver.common.keys import Keys

#시간에 따른 컨트롤이 가능한 라이브러리 불러오기
import time

In [ ]:
#시군구 선택 
browser.find_element("xpath","/html/body/div[1]/div[2]/div[1]/div[2]/div/div/div[1]/div/div[1]/ul/li[1]/div/div[2]/a").click()

In [ ]:
itemlist = browser.find_element("xpath", "/html/body/div[2]/div/div[2]/div/div[1]/div/ul/li[1]/div")

In [ ]:
browser.execute_script("arguments[0].scrollBy(0, document.body.scrollHeight);", itemlist)

In [ ]:
#전북 선택
browser.find_element("xpath", "/html/body/div[2]/div/div[2]/div/div[1]/div/ul/li[1]/div/ul/li[14]/label").click()

In [ ]:
#확인 선택
browser.find_element("xpath","/html/body/div[2]/div/div[2]/div/div[2]/a[2]/span").click()

In [ ]:
#현황보기 선택 
browser.find_element("xpath","/html/body/div[1]/div[2]/div[1]/div[2]/div/div/div[1]/div/div[2]/a").click()

In [ ]:
jnorth_table = browser.find_elements(By.CSS_SELECTOR,'#tableBody > tr > td')
jnorth_result = []
for a in jnorth_table:
  jnorth_result.append(a.text)

In [ ]:
#리스트 분할 함수
def list_chunk(lst, n):
  return [lst[i:i+n] for i in range(0, len(lst), n)]

In [ ]:
jnorth_result = list_chunk(jnorth_result, 9) # 한번만 실행할 것!
jnorth_result

In [ ]:
jnorth_df = pd.DataFrame(jnorth_result, columns = mycolumns)
jnorth_df

,행정구역,총가구수,총인구수,주요시설수,집객시설수,아파트 면적(1m²)당 기준시가(원),업소수,업소당 가구수,업소당 시설물수
0,전라북도,"787,531","1,870,445","11,666","12,805","3,355,622","121,687",6,0.2
1,┗ 전주시,"256,592","653,335","3,345","4,307","3,912,129","45,510",6,0.17
2,┗ 군산시,"116,372","282,292","1,558","1,891","3,131,228","19,159",6,0.18
3,┗ 익산시,"123,256","301,499","1,618","1,765","2,838,646","19,790",6,0.17
4,┗ 정읍시,"52,247","115,568",992,781,"2,901,280","7,085",7,0.25
5,┗ 남원시,"37,329","84,725",554,731,"3,070,568","6,347",6,0.2
6,┗ 김제시,"41,613","88,611",865,526,"2,827,977","4,696",9,0.3
7,┗ 완주군,"41,019","95,590",519,575,"3,618,763","4,665",9,0.23
8,┗ 진안군,"12,618","26,066",254,194,"2,188,626","1,345",9,0.33
9,┗ 무주군,"11,829","25,101",213,368,"2,521,111","1,991",6,0.29
10,┗ 장수군,"10,973","23,265",165,155,"1,954,249","1,170",9,0.27
11,┗ 임실군,"14,111","29,322",282,231,"2,286,952","1,843",8,0.28
12,┗ 순창군,"13,590","29,364",296,231,"2,721,695","1,500",9,0.35
13,┗ 고창군,"28,582","59,188",506,486,"3,064,238","3,136",9,0.32
14,┗ 부안군,"27,401","56,518",499,564,"2,916,054","3,450",8,0.31

In [282]:
jnorth_df.to_csv("전북_지역현황.csv", index = None)

#### 전남

In [ ]:
#시군구 선택 
browser.find_element("xpath","/html/body/div[1]/div[2]/div[1]/div[2]/div/div/div[1]/div/div[1]/ul/li[1]/div/div[2]/a").click()

In [ ]:
itemlist = browser.find_element("xpath", "/html/body/div[2]/div/div[2]/div/div[1]/div/ul/li[1]/div")

In [ ]:
browser.execute_script("arguments[0].scrollBy(0, document.body.scrollHeight);", itemlist)

In [ ]:
#전남 선택
browser.find_element("xpath", "/html/body/div[2]/div/div[2]/div/div[1]/div/ul/li[1]/div/ul/li[15]/label").click()

In [ ]:
#확인 선택
browser.find_element("xpath","/html/body/div[2]/div/div[2]/div/div[2]/a[2]/span").click()

In [ ]:
#현황보기 선택 
browser.find_element("xpath","/html/body/div[1]/div[2]/div[1]/div[2]/div/div/div[1]/div/div[2]/a").click()

In [ ]:
jsouth_table = browser.find_elements(By.CSS_SELECTOR,'#tableBody > tr > td')
jsouth_result = []
for a in jsouth_table:
  jsouth_result.append(a.text)

In [ ]:
jsouth_result = list_chunk(jsouth_result, 9) # 한번만 실행할 것!
jsouth_result

In [ ]:
jsouth_df = pd.DataFrame(jsouth_result, columns = mycolumns)
jsouth_df

In [283]:
jsouth_df.to_csv("전남_지역현황.csv", index = None)

In [ ]:
all_df = pd.concat([kj_df, tk_df, jnorth_df, jsouth_df], axis = 0)

In [ ]:
all_df

,행정구역,총가구수,총인구수,주요시설수,집객시설수,아파트 면적(1m²)당 기준시가(원),업소수,업소당 가구수,업소당 시설물수
0,광주광역시,"585,113","1,476,513","6,464","7,782","4,909,203","82,825",7,0.17
1,┗ 동구,"42,900","91,393",722,"1,099","3,663,949","10,468",4,0.17
2,┗ 서구,"122,089","308,479","1,472","1,910","5,206,981","20,172",6,0.17
3,┗ 남구,"88,114","222,181",952,800,"4,941,637","9,057",10,0.19
4,┗ 북구,"181,737","450,822","1,853","2,257","4,598,536","23,337",8,0.18
5,┗ 광산구,"150,274","403,638","1,465","1,716","5,365,703","19,791",8,0.16
0,대구광역시,"988,192","2,489,558","8,842","10,578","5,160,656","119,160",8,0.16
1,┗ 중구,"38,554","81,042",831,"1,363","4,788,566","13,157",3,0.17
2,┗ 동구,"145,733","351,127","1,195","1,514","4,559,584","15,729",9,0.17
3,┗ 서구,"89,212","203,338",734,814,"3,781,196","9,465",9,0.16
4,┗ 남구,"74,465","159,101",647,798,"4,116,710","8,465",9,0.17
5,┗ 북구,"169,997","440,951","1,404","1,580","5,464,788","18,608",9,0.16
6,┗ 수성구,"165,591","449,558","1,578","1,450","6,778,187","19,938",8,0.15
7,┗ 달서구,"225,337","597,720","1,764","2,314","5,856,351","25,557",9,0.16
8,┗ 달성군,"79,302","206,723",689,745,"5,019,088","8,241",10,0.17
0,전라북도,"787,531","1,870,445","11,666","12,805","3,355,622","121,687",6,0.2
1,┗ 전주시,"256,592","653,335","3,345","4,307","3,912,129","45,510",6,0.17
2,┗ 군산시,"116,372","282,292","1,558","1,891","3,131,228","19,159",6,0.18
3,┗ 익산시,"123,256","301,499","1,618","1,765","2,838,646","19,790",6,0.17
4,┗ 정읍시,"52,247","115,568",992,781,"2,901,280","7,085",7,0.25
5,┗ 남원시,"37,329","84,725",554,731,"3,070,568","6,347",6,0.2
6,┗ 김제시,"41,613","88,611",865,526,"2,827,977","4,696",9,0.3
7,┗ 완주군,"41,019","95,590",519,575,"3,618,763","4,665",9,0.23
8,┗ 진안군,"12,618","26,066",254,194,"2,188,626","1,345",9,0.33
9,┗ 무주군,"11,829","25,101",213,368,"2,521,111","1,991",6,0.29
10,┗ 장수군,"10,973","23,265",165,155,"1,954,249","1,170",9,0.27
11,┗ 임실군,"14,111","29,322",282,231,"2,286,952","1,843",8,0.28
12,┗ 순창군,"13,590","29,364",296,231,"2,721,695","1,500",9,0.35
13,┗ 고창군,"28,582","59,188",506,486,"3,064,238","3,136",9,0.32
14,┗ 부안군,"27,401","56,518",499,564,"2,916,054","3,450",8,0.31
0,전라남도,"839,868","1,910,594","11,690","13,570","3,045,145","122,937",7,0.21
1,┗ 목포시,"103,125","244,125","1,155","1,732","3,141,147","17,379",6,0.17
2,┗ 여수시,"118,017","288,823","1,466","2,053","3,324,116","19,179",6,0.18
3,┗ 순천시,"109,561","281,610","1,472","2,111","3,503,794","22,988",5,0.16
4,┗ 나주시,"48,145","101,937",665,689,"3,646,949","5,514",9,0.25
5,┗ 광양시,"60,144","153,232",623,954,"2,508,693","10,440",6,0.15
6,┗ 담양군,"22,230","47,126",398,353,"3,231,377","2,505",9,0.3
7,┗ 곡성군,"15,082","30,686",221,222,"2,679,224","1,590",9,0.28
8,┗ 구례군,"12,718","27,250",279,339,"2,113,565","2,304",6,0.27
9,┗ 고흥군,"34,614","68,309",584,582,"1,842,000","4,168",8,0.28
10,┗ 보성군,"22,452","44,847",386,364,"2,036,633","2,783",8,0.27
11,┗ 화순군,"29,492","65,717",432,352,"3,401,660","3,375",9,0.23
12,┗ 장흥군,"20,185","40,955",354,347,"2,762,055","2,659",8,0.26
13,┗ 강진군,"18,497","38,316",251,312,"2,474,554","2,224",8,0.25
14,┗ 해남군,"35,326","75,702",502,483,"2,925,165","4,283",8,0.23
15,┗ 영암군,"27,445","58,262",385,414,"2,272,394","3,189",9,0.25
16,┗ 무안군,"34,096","78,829",441,439,"4,111,896","4,214",8,0.21
17,┗ 함평군,"17,603","34,675",255,174,"3,361,124","1,515",12,0.28
18,┗ 영광군,"26,050","55,906",463,377,"2,686,811","3,529",7,0.24
19,┗ 장성군,"21,516","46,357",342,305,"2,592,344","2,220",10,0.29
20,┗ 완도군,"25,575","52,718",413,479,"3,178,508","3,302",8,0.27
21,┗ 진도군,"15,872","32,226",284,244,"2,154,050","1,927",8,0.27
22,┗ 신안군,"22,125","42,984",319,245,"2,434,460","1,650",13,0.34

In [284]:
all_df.to_csv("전체_지역현황.csv", index = None)

In [ ]:
browser.close()

### 업소현황

#### 광주

In [ ]:
# 웹 드라이버 객체 생성
browser = webdriver.Chrome('chromedriver', options = options)

In [ ]:
browser.get('https://sg.sbiz.or.kr/godo/stat/upso.sg')

In [ ]:
#시군구 선택
browser.find_element("xpath","/html/body/div[1]/div[2]/div[1]/div[2]/div/div/div[1]/div/div[1]/ul/li[1]/div/div[2]/a").click()

In [ ]:
#광주 선택 
browser.find_element("xpath","/html/body/div[2]/div/div[2]/div/div[1]/div/ul/li[1]/div/ul/li[6]/label").click()

In [ ]:
#확인 선택
browser.find_element("xpath","/html/body/div[2]/div/div[2]/div/div[2]/a[2]/span").click()

In [ ]:
#현황보기 선택 
browser.find_element("xpath","/html/body/div[1]/div[2]/div[1]/div[2]/div/div/div[1]/div/div[2]/a").click()

In [ ]:
kj_table2 = browser.find_elements(By.CSS_SELECTOR,'#upsoTable > tr > td')
kj_result2 = []
for a in kj_table2:
  kj_result2.append(a.text)

In [ ]:
kj_result2 = list_chunk(kj_result2, 4) # 한번만 실행할 것!
kj_result2

[['광주광역시', '77,220', '74,004', '-4.16%'],
 ['┗ 동구', '9,044', '8,921', '-1.36%'],
 ['┗ 서구', '18,408', '15,607', '-15.22%'],
 ['┗ 남구', '9,171', '8,798', '-4.07%'],
 ['┗ 북구', '21,419', '21,271', '-0.69%'],
 ['┗ 광산구', '18,766', '18,898', '0.7%']]

In [ ]:
mycolumns2 = ["행정구역", "2021년 상반기", "2021년 하반기", "증감률"]

In [ ]:
kj_df2 = pd.DataFrame(kj_result2, columns = mycolumns2)
kj_df2

    행정구역 2021년 상반기 2021년 하반기      증감률
0  광주광역시    77,220    74,004   -4.16%
1   ┗ 동구     9,044     8,921   -1.36%
2   ┗ 서구    18,408    15,607  -15.22%
3   ┗ 남구     9,171     8,798   -4.07%
4   ┗ 북구    21,419    21,271   -0.69%
5  ┗ 광산구    18,766    18,898     0.7%

In [285]:
kj_df2.to_csv("광주_업소현황.csv", index = None)

#### 대구

In [ ]:
#시군구 선택
browser.find_element("xpath","/html/body/div[1]/div[2]/div[1]/div[2]/div/div/div[1]/div/div[1]/ul/li[1]/div/div[2]/a").click()

In [ ]:
#대구 선택 
browser.find_element("xpath","/html/body/div[2]/div/div[2]/div/div[1]/div/ul/li[1]/div/ul/li[4]/label").click()

In [ ]:
#확인 선택
browser.find_element("xpath","/html/body/div[2]/div/div[2]/div/div[2]/a[2]/span").click()

In [ ]:
#현황보기 선택 
browser.find_element("xpath","/html/body/div[1]/div[2]/div[1]/div[2]/div/div/div[1]/div/div[2]/a").click()

In [ ]:
tk_table2 = browser.find_elements(By.CSS_SELECTOR,'#upsoTable > tr > td')
tk_result2 = []
for a in tk_table2:
  tk_result2.append(a.text)

In [ ]:
tk_result2 = list_chunk(tk_result2, 4) # 한번만 실행할 것!

In [ ]:
tk_df2 = pd.DataFrame(tk_result2, columns = mycolumns2)
tk_df2

    행정구역 2021년 상반기 2021년 하반기      증감률
0  대구광역시   113,856   108,176   -4.99%
1   ┗ 중구    14,036    12,207  -13.03%
2   ┗ 동구    15,801    15,548    -1.6%
3   ┗ 서구     8,591     8,446   -1.69%
4   ┗ 남구     7,531     7,349   -2.42%
5   ┗ 북구    18,474    17,081   -7.54%
6  ┗ 수성구    17,743    15,620  -11.97%
7  ┗ 달서구    22,221    21,942   -1.26%
8  ┗ 달성군     8,753     9,039    3.27%

In [286]:
tk_df2.to_csv("대구_업소현황.csv", index = None)

#### 전북

In [ ]:
#시군구 선택
browser.find_element("xpath","/html/body/div[1]/div[2]/div[1]/div[2]/div/div/div[1]/div/div[1]/ul/li[1]/div/div[2]/a").click()

In [ ]:
itemlist = browser.find_element("xpath", "/html/body/div[2]/div/div[2]/div/div[1]/div/ul/li[1]/div")

In [ ]:
browser.execute_script("arguments[0].scrollBy(0, document.body.scrollHeight);", itemlist)

In [ ]:
#전북 선택 
browser.find_element("xpath","/html/body/div[2]/div/div[2]/div/div[1]/div/ul/li[1]/div/ul/li[14]/label").click()

In [ ]:
#확인 선택
browser.find_element("xpath","/html/body/div[2]/div/div[2]/div/div[2]/a[2]/span").click()

In [ ]:
#현황보기 선택 
browser.find_element("xpath","/html/body/div[1]/div[2]/div[1]/div[2]/div/div/div[1]/div/div[2]/a").click()

In [ ]:
jnorth_table2 = browser.find_elements(By.CSS_SELECTOR,'#upsoTable > tr > td')
jnorth_result2 = []
for a in jnorth_table2:
  jnorth_result2.append(a.text)

In [ ]:
jnorth_result2 = list_chunk(jnorth_result2, 4) # 한번만 실행할 것!

In [ ]:
jnorth_df2 = pd.DataFrame(jnorth_result2, columns = mycolumns2)
jnorth_df2

     행정구역 2021년 상반기 2021년 하반기     증감률
0    전라북도   125,416   120,982  -3.54%
1   ┗ 전주시    45,234    43,818  -3.13%
2   ┗ 군산시    18,693    16,786  -10.2%
3   ┗ 익산시    20,303    19,543  -3.74%
4   ┗ 정읍시     7,469     7,373  -1.29%
5   ┗ 남원시     6,544     6,290  -3.88%
6   ┗ 김제시     5,324     5,249  -1.41%
7   ┗ 완주군     5,210     5,199  -0.21%
8   ┗ 진안군     1,612     1,586  -1.61%
9   ┗ 무주군     2,103     2,077  -1.24%
10  ┗ 장수군     1,227     1,211   -1.3%
11  ┗ 임실군     1,959     1,898  -3.11%
12  ┗ 순창군     1,728     1,700  -1.62%
13  ┗ 고창군     3,311     3,269  -1.27%
14  ┗ 부안군     4,012     3,960   -1.3%

In [287]:
jnorth_df2.to_csv("전북_업소현황.csv", index = None)

#### 전남

In [ ]:
#시군구 선택
browser.find_element("xpath","/html/body/div[1]/div[2]/div[1]/div[2]/div/div/div[1]/div/div[1]/ul/li[1]/div/div[2]/a").click()

In [ ]:
itemlist = browser.find_element("xpath", "/html/body/div[2]/div/div[2]/div/div[1]/div/ul/li[1]/div")

In [ ]:
browser.execute_script("arguments[0].scrollBy(0, document.body.scrollHeight);", itemlist)

In [ ]:
#전남 선택 
browser.find_element("xpath","/html/body/div[2]/div/div[2]/div/div[1]/div/ul/li[1]/div/ul/li[15]/label").click()

In [ ]:
#확인 선택
browser.find_element("xpath","/html/body/div[2]/div/div[2]/div/div[2]/a[2]/span").click()

In [ ]:
#현황보기 선택 
browser.find_element("xpath","/html/body/div[1]/div[2]/div[1]/div[2]/div/div/div[1]/div/div[2]/a").click()

In [ ]:
jsouth_table2 = browser.find_elements(By.CSS_SELECTOR,'#upsoTable > tr > td')
jsouth_result2 = []
for a in jsouth_table2:
  jsouth_result2.append(a.text)

In [ ]:
jsouth_result2 = list_chunk(jsouth_result2, 4) # 한번만 실행할 것!

In [ ]:
jsouth_df2 = pd.DataFrame(jsouth_result2, columns = mycolumns2)
jsouth_df2

     행정구역 2021년 상반기 2021년 하반기      증감률
0    전라남도   129,663   126,004   -2.82%
1   ┗ 목포시    17,103    16,517   -3.43%
2   ┗ 여수시    19,623    19,074    -2.8%
3   ┗ 순천시    22,269    21,343   -4.16%
4   ┗ 나주시     6,123     4,985  -18.59%
5   ┗ 광양시    10,224    10,094   -1.27%
6   ┗ 담양군     2,899     2,854   -1.55%
7   ┗ 곡성군     1,841     1,796   -2.44%
8   ┗ 구례군     2,508     2,485   -0.92%
9   ┗ 고흥군     4,360     4,342   -0.41%
10  ┗ 보성군     3,174     3,114   -1.89%
11  ┗ 화순군     3,819     3,375  -11.63%
12  ┗ 장흥군     2,781     2,765   -0.58%
13  ┗ 강진군     2,558     2,533   -0.98%
14  ┗ 해남군     4,822     4,831    0.19%
15  ┗ 영암군     3,606     3,546   -1.66%
16  ┗ 무안군     4,948     4,887   -1.23%
17  ┗ 함평군     1,650     1,629   -1.27%
18  ┗ 영광군     3,771     3,737    -0.9%
19  ┗ 장성군     2,760     2,730   -1.09%
20  ┗ 완도군     3,717     3,708   -0.24%
21  ┗ 진도군     2,051     2,054    0.15%
22  ┗ 신안군     2,060     2,079    0.92%

In [289]:
jsouth_df2.to_csv("전남_업소현황.csv", index = None)

In [ ]:
all_df2 = pd.concat([kj_df2, tk_df2, jnorth_df2, jsouth_df2], axis = 0)

In [ ]:
all_df2.reset_index()

    index   행정구역 2021년 상반기 2021년 하반기      증감률
0       0  광주광역시    77,220    74,004   -4.16%
1       1   ┗ 동구     9,044     8,921   -1.36%
2       2   ┗ 서구    18,408    15,607  -15.22%
3       3   ┗ 남구     9,171     8,798   -4.07%
4       4   ┗ 북구    21,419    21,271   -0.69%
5       5  ┗ 광산구    18,766    18,898     0.7%
6       0  대구광역시   113,856   108,176   -4.99%
7       1   ┗ 중구    14,036    12,207  -13.03%
8       2   ┗ 동구    15,801    15,548    -1.6%
9       3   ┗ 서구     8,591     8,446   -1.69%
10      4   ┗ 남구     7,531     7,349   -2.42%
11      5   ┗ 북구    18,474    17,081   -7.54%
12      6  ┗ 수성구    17,743    15,620  -11.97%
13      7  ┗ 달서구    22,221    21,942   -1.26%
14      8  ┗ 달성군     8,753     9,039    3.27%
15      0   전라북도   125,416   120,982   -3.54%
16      1  ┗ 전주시    45,234    43,818   -3.13%
17      2  ┗ 군산시    18,693    16,786   -10.2%
18      3  ┗ 익산시    20,303    19,543   -3.74%
19      4  ┗ 정읍시     7,469     7,373   -1.29%
20      5  ┗ 남원시     6,544     6,290   -3.88%
21      6  ┗ 김제시     5,324     5,249   -1.41%
22      7  ┗ 완주군     5,210     5,199   -0.21%
23      8  ┗ 진안군     1,612     1,586   -1.61%
24      9  ┗ 무주군     2,103     2,077   -1.24%
25     10  ┗ 장수군     1,227     1,211    -1.3%
26     11  ┗ 임실군     1,959     1,898   -3.11%
27     12  ┗ 순창군     1,728     1,700   -1.62%
28     13  ┗ 고창군     3,311     3,269   -1.27%
29     14  ┗ 부안군     4,012     3,960    -1.3%
30      0   전라남도   129,663   126,004   -2.82%
31      1  ┗ 목포시    17,103    16,517   -3.43%
32      2  ┗ 여수시    19,623    19,074    -2.8%
33      3  ┗ 순천시    22,269    21,343   -4.16%
34      4  ┗ 나주시     6,123     4,985  -18.59%
35      5  ┗ 광양시    10,224    10,094   -1.27%
36      6  ┗ 담양군     2,899     2,854   -1.55%
37      7  ┗ 곡성군     1,841     1,796   -2.44%
38      8  ┗ 구례군     2,508     2,485   -0.92%
39      9  ┗ 고흥군     4,360     4,342   -0.41%
40     10  ┗ 보성군     3,174     3,114   -1.89%
41     11  ┗ 화순군     3,819     3,375  -11.63%
42     12  ┗ 장흥군     2,781     2,765   -0.58%
43     13  ┗ 강진군     2,558     2,533   -0.98%
44     14  ┗ 해남군     4,822     4,831    0.19%
45     15  ┗ 영암군     3,606     3,546   -1.66%
46     16  ┗ 무안군     4,948     4,887   -1.23%
47     17  ┗ 함평군     1,650     1,629   -1.27%
48     18  ┗ 영광군     3,771     3,737    -0.9%
49     19  ┗ 장성군     2,760     2,730   -1.09%
50     20  ┗ 완도군     3,717     3,708   -0.24%
51     21  ┗ 진도군     2,051     2,054    0.15%
52     22  ┗ 신안군     2,060     2,079    0.92%

In [288]:
all_df2.to_csv("전체_업소현황.csv", index = None)

In [ ]:
browser.close()